### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by kybishop** [kybishop/ember-popper#2]
We should have a test for each option that we can pass into ember-popper. For things already heavily tested in popper.js, like `placement`, a simple smoke test to ensure that the option is passed through correctly should suffice.

Caveat: No jquery please.

- [x] eventsEnabled (smoke test) [#26]
- [x] modifiers (smoke test) [#25]
- [x] placement (smoke test) [#22]
- [x] ~popperClass (smoke test is acceptable for this since it is so simple)~ (nixing this since we plan to use `class` instead of `popperClass`)
- [x] popperContainer [#21]
- [x] renderInPlace [#21]
- [x] target [#24]

If you'd like to tackle one of these tests, leave a comment mentioning that you are working on it

**Comment by FezVrasta** [comment]
Take in account that Popper.js, unlike Tether, has already a very solid test suite on its own. You just need to test the integration that this library provides with Ember.
